spring:
  application:
    name: linhai-agent

  profiles:
    active: dev

# SpringAI配置 根据客户端名称 快速切换不同服务商提供的大模型服务
  ai:
    dashscope:
      api-key: " " # todo 填写你的阿里云百炼api-Key https://dashscope.console.aliyun.com/apiKey
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434 # ollama模型本地启动默认api端口
      chat:
        model: qwen4:8b # 填写你自己的ollama运行模型名
    # 阿里云 dashscope 向量存储配置
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536 # 按照你的embedding模型参数设置向量维度相关数据
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  # 填写你的阿里云 Postgresql 线上数据库地址
  datasource:
    url: jdbc:postgresql://填写你的pg数据库地址:5432/linhai-ai-agent
    username: linhai
    password:

server:
  port: 8080
  servlet:
    context-path: /api

# swagger接口文档相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.linhai.linhai_agent.controller

# knife4j增强接口文档相关配置
knife4j:
  enable: true
  setting:
    language: zh_cn

